export const MenPRODUCT_LIST_REQUEST = "MenPRODUCT_LIST_REQUEST";
export const MenPRODUCT_LIST_SUCCESS = "MenPRODUCT_LIST_SUCCESS";
export const MenPRODUCT_LIST_FAIL = "MenPRODUCT_LIST_FAIL";

export const MenPRODUCT_DETAILS_REQUEST = "MenPRODUCT_DETAILS_REQUEST";
export const MenPRODUCT_DETAILS_SUCCESS = "MenPRODUCT_DETAILS_SUCCESS";
export const MenPRODUCT_DETAILS_FAIL = "MenPRODUCT_DETAILS_FAIL";

export const MenPRODUCT_CREATE_REVIEW_REQUEST = "MenPRODUCT_CREATE_REVIEW_REQUEST";
export const MenPRODUCT_CREATE_REVIEW_SUCCESS = "MenPRODUCT_CREATE_REVIEW_SUCCESS";
export const MenPRODUCT_CREATE_REVIEW_FAIL = "MenPRODUCT_CREATE_REVIEW_FAIL";
export const MenPRODUCT_CREATE_REVIEW_RESET = "MenPRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";


export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const ADMIN_MEN_PRODUCT_REQUEST = "ADMIN_MEN_PRODUCT_REQUEST";
export const ADMIN_MEN_PRODUCT_SUCCESS = "ADMIN_MEN_PRODUCT_SUCCESS";
export const ADMIN_MEN_PRODUCT_FAIL = "ADMIN_MEN_PRODUCT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";