export const WomenPRODUCT_LIST_REQUEST = "WomenPRODUCT_LIST_REQUEST";
export const WomenPRODUCT_LIST_SUCCESS = "WomenPRODUCT_LIST_SUCCESS";
export const WomenPRODUCT_LIST_FAIL = "WomenPRODUCT_LIST_FAIL";

export const WomenPRODUCT_DETAILS_REQUEST = "WomenPRODUCT_DETAILS_REQUEST";
export const WomenPRODUCT_DETAILS_SUCCESS = "WomenPRODUCT_DETAILS_SUCCESS";
export const WomenPRODUCT_DETAILS_FAIL = "WomenPRODUCT_DETAILS_FAIL";

export const WomenPRODUCT_CREATE_REVIEW_REQUEST = "WomenPRODUCT_CREATE_REVIEW_REQUEST";
export const WomenPRODUCT_CREATE_REVIEW_SUCCESS = "WomenPRODUCT_CREATE_REVIEW_SUCCESS";
export const WomenPRODUCT_CREATE_REVIEW_FAIL = "WomenPRODUCT_CREATE_REVIEW_FAIL";
export const WomenPRODUCT_CREATE_REVIEW_RESET = "WomenPRODUCT_CREATE_REVIEW_RESET";



export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";


export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";


export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const ADMIN_WOMEN_PRODUCT_REQUEST = "ADMIN_WOMEN_PRODUCT_REQUEST";
export const ADMIN_WOMEN_PRODUCT_SUCCESS = "ADMIN_WOMEN_PRODUCT_SUCCESS";
export const ADMIN_WOMEN_PRODUCT_FAIL = "ADMIN_WOMEN_PRODUCT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";